# Naive Bayes Project

## Project Overview
This notebook demonstrates text classification using the Naive Bayes algorithm.

### Objectives
- Load and explore the dataset.
- Preprocess the text data.
- Convert text into numerical features.
- Train a Naive Bayes classifier.
- Evaluate the model using performance metrics.
- Make predictions on new samples.

### About Naive Bayes
Naive Bayes is a probabilistic machine learning algorithm based on Bayes' Theorem. It assumes that all input features are independent of each other, making it simple, fast, and highly effective for text classification tasks such as spam detection and sentiment analysis.

In [1]:
import numpy as np
import pandas as pd
import sklearn
train_docs = pd.read_csv('example_train.csv') 
train_docs

                                            Document      Class
0  Future Vision Computer Institute is a great ed...  education
1            Educational greatness depends on ethics  education
2  A story of great ethics and educational greatness  education
3                           Sholey is a great cinema     cinema
4                   good movie depends on good story     cinema

## Dataset Loading
This code imports the dataset into a Pandas DataFrame so it can be explored and processed.

In [2]:
train_docs['Class'] = train_docs.Class.map({'cinema':0, 'education':1})
train_docs

                                            Document  Class
0  Future Vision Computer Institute is a great ed...      1
1            Educational greatness depends on ethics      1
2  A story of great ethics and educational greatness      1
3                           Sholey is a great cinema      0
4                   good movie depends on good story      0

In [3]:
train_array = train_docs.values

X_train = train_array[:,0]
y_train = train_array[:,1]
y_train = y_train.astype('int') 

print("X_train")
print(X_train)
print("y_train")
print(y_train)

X_train
['Future Vision Computer Institute is a great educational institution.'
 'Educational greatness depends on ethics'
 'A story of great ethics and educational greatness'
 'Sholey is a great cinema' 'good movie depends on good story']
y_train
[1 1 1 0 0]

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

## Feature Extraction
Text data is converted into numerical vectors using vectorization techniques so machine learning algorithms can process it.

In [5]:
vec = CountVectorizer()

## Feature Extraction
Text data is converted into numerical vectors using vectorization techniques so machine learning algorithms can process it.

In [6]:
vec.fit(X_train)
vec.vocabulary_

{'future': 6,
 'vision': 18,
 'computer': 2,
 'institute': 10,
 'is': 12,
 'great': 8,
 'educational': 4,
 'institution': 11,
 'greatness': 9,
 'depends': 3,
 'on': 15,
 'ethics': 5,
 'story': 17,
 'of': 14,
 'and': 0,
 'sholey': 16,
 'cinema': 1,
 'good': 7,
 'movie': 13}

In [7]:
vec = CountVectorizer(stop_words='english')
vec.fit(X_train)
vec.vocabulary_

{'future': 5,
 'vision': 14,
 'computer': 1,
 'institute': 9,
 'great': 7,
 'educational': 3,
 'institution': 10,
 'greatness': 8,
 'depends': 2,
 'ethics': 4,
 'story': 13,
 'sholey': 12,
 'cinema': 0,
 'good': 6,
 'movie': 11}

## Feature Extraction
Text data is converted into numerical vectors using vectorization techniques so machine learning algorithms can process it.

In [9]:
print(vec.get_feature_names_out())
print(len(vec.get_feature_names_out()))

['cinema' 'computer' 'depends' 'educational' 'ethics' 'future' 'good'
 'great' 'greatness' 'institute' 'institution' 'movie' 'sholey' 'story'
 'vision']
15

In [11]:
X_transformed = vec.transform(X_train)
X_transformed

<5x15 sparse matrix of type '<class 'numpy.int64'>'
	with 23 stored elements in Compressed Sparse Row format>

In [12]:
print(X_transformed)

  (0, 1)	1
  (0, 3)	1
  (0, 5)	1
  (0, 7)	1
  (0, 9)	1
  (0, 10)	1
  (0, 14)	1
  (1, 2)	1
  (1, 3)	1
  (1, 4)	1
  (1, 8)	1
  (2, 3)	1
  (2, 4)	1
  (2, 7)	1
  (2, 8)	1
  (2, 13)	1
  (3, 0)	1
  (3, 7)	1
  (3, 12)	1
  (4, 2)	1
  (4, 6)	2
  (4, 11)	1
  (4, 13)	1

In [13]:
X_transformed.toarray()

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1],
       [0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 1, 0]], dtype=int64)

In [14]:
pd.DataFrame(X_transformed.toarray(), 
             columns=vec.get_feature_names_out())

,cinema,computer,depends,educational,ethics,future,good,great,greatness,institute,institution,movie,sholey,story,vision
0,0,1,0,1,0,1,0,1,0,1,1,0,0,0,1
1,0,0,1,1,1,0,0,0,1,0,0,0,0,0,0
2,0,0,0,1,1,0,0,1,1,0,0,0,0,1,0
3,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0
4,0,0,1,0,0,0,2,0,0,0,0,1,0,1,0

In [15]:
test_docs = pd.read_csv('example_test.csv') 
test_docs

                            Document      Class
0  very good educational institution  education

## Dataset Loading
This code imports the dataset into a Pandas DataFrame so it can be explored and processed.

In [16]:
test_docs['Class'] = test_docs.Class.map({'cinema':0, 'education':1})
test_docs

                            Document  Class
0  very good educational institution      1

In [17]:
test_numpy_array = test_docs.values

X_test = test_numpy_array[:,0]
y_test = test_numpy_array[:,1]

print("X_test")
print(X_test)
print("y_test")
print(y_test)

X_test
['very good educational institution']
y_test
[1]

In [18]:
X_test_transformed = vec.transform(X_test)
X_test_transformed

<1x15 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [20]:
X_test = X_test_transformed.toarray()
X_test

array([[0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0]], dtype=int64)

In [21]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X_transformed, y_train)
proba = mnb.predict_proba(X_test)

## Model Training
The Naive Bayes classifier is trained using the training data to learn patterns between features and target labels.

In [22]:
print("probability of test document belonging to class CINEMA", proba[:,0])
print("probability of test document belonging to class EDUCATION", proba[:,1])

probability of test document belonging to class CINEMA [0.3797015]
probability of test document belonging to class EDUCATION [0.6202985]

In [23]:
from sklearn.naive_bayes import BernoulliNB

# instantiating bernoulli NB class
bnb=BernoulliNB()

# fitting the model
bnb.fit(X_transformed, y_train)

bnb.predict_proba(X_test)
prob_bnb = bnb.predict_proba(X_test)
prob_bnb

array([[0.37190622, 0.62809378]])

## Model Training
The Naive Bayes classifier is trained using the training data to learn patterns between features and target labels.